### Doc Swagger
GET http://localhost:5001/api-docs/

### Website in PUG
GET http://localhost:5001

### Accueil API
GET http://localhost:5001/api/

//---------------//

### Liste manufacturers
GET http://localhost:5001/api/manufacturers

### Manufacturer by Id (2) - teams associées
GET http://localhost:5001/api/manufacturers/3

//---------------//

### Liste teams
GET http://localhost:5001/api/teams

### Team by Id (8)
GET http://localhost:5001/api/teams/8

//---------------//

### Liste pilots
GET http://localhost:5001/api/pilots

### Pilot by Id (23)
GET http://localhost:5001/api/pilots/23

# ### Pilot by Name (Quartararo) A TESTER + TARD
# GET http://localhost:5001/api/pilots/quartararo


//---------------//

### Liste racetracks
GET http://localhost:5001/api/racetracks

### Racetrack by Id (9)
GET http://localhost:5001/api/racetracks/9

//---------------//

### Liste races
GET http://localhost:5001/api/races

### Race by Id (10)
GET http://localhost:5001/api/races/10

//-----------------------//

# ### Test APIGeocoding - donne le résultat complet de la requete
# GET http://www.mapquestapi.com/geocoding/v1/address?key={{$dotenv API_MAP_KEY}}&location=Lauris

# ### Test APIWeather - météo du jour (pour avant c'est payant)
# GET https://api.openweathermap.org/data/2.5/onecall/timemachine?lat=30.264979&lon=-97.746598&dt=1644212551&appid={{$dotenv API_WEATHER_KEY}}
